class Program {
	public static void main(String[] args) {
	int x5000, x1000, x500, x200, x100, x50, x10, x5, x2, x1;
	int number = 13765;
	x5000 = number / 5000;
	x1000 = number / 1000;
	x500 = number / 500;
	x200 = number / 200;
	x100 = number / 100;
	x50 = number / 50;
	x10 = number / 10;
	x5 = number / 5;
	x2 =number / 2;
	x1 = number / 1;
	System.out.println("5000-" + x5000 + " " + "1000-" + x1000 + " " +"500-" + x500 + " " + "200-" + x200 + " " + "100-" + x100 + " " + "50-" + x50 + " " + "10-" + x10 + " " + "5-" + x5 + " " + "2-" + x2 + " " + "1-" + x1);

	}
}